version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "masa10-f"
    ignore:
      - dependency-name: "numpy"
        update-types: ["version-update:semver-major"]
