name: doc

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install --upgrade pip

      - run: pip install -v -e .[dev]

      - name: Make docs
        run: sphinx-build -W docs/source docs/build

      - name: Save docs
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/build
