name: mypy

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  typecheck-mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - run: |
          python3 -m pip install -U pip
          pip install .[dev]
          mypy
