name: pyright

on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  typecheck-pyright:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: rustup update

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Run pyright
        run: |
          python3 -m pip install -U pip
          pip install pyright pytest
          pip install .
          pyright
