name: ruff

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ruff_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: chartboost/ruff-action@v1

  ruff_format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: chartboost/ruff-action@v1
        with:
          args: "format --check"

      - uses: chartboost/ruff-action@v1
        with:
          args: "check --select I"
